Ice in blk_1m
igfuw/libcloudphxx pull request #455
Opened 2024-10-29 11:52 UTC by AgnieszkaMakulska

2024-10-30 11:54 UTC, pdziekan requested changes
Great PR, had some minor comments

2024-10-30 11:54 UTC, pdziekan commented on CMakeLists.txt
zmiany cmakelists pewnie spowoduja bledy w kompilacji na innych maszynach - mozemy zobaczyc, czy testy GA przejda

2024-10-30 11:54 UTC, pdziekan commented on cmake/FindThrust.cmake
Plik jest do przywrocenia. To jest przepis na znajdowanie thrusta przez cmake. Sciezka do niego jest dodawana w CmakeLists.txt: 
``` 
list(INSERT CMAKE_MODULE_PATH 0 ${PROJECT_SOURCE_DIR}/cmake)
```

2024-10-30 11:54 UTC, pdziekan commented on bindings/python/blk_1m.hpp
Czy mozesz poprawic wciecia w tym pliku? Od dawna sa zle, bo uzywaja tabulatorow. Nasza strategia jest taka, zeby uzywac tylko spacji (dwie spacje na wciecie).

2024-10-30 11:54 UTC, pdziekan commented on cmake/LICENSE_VTKm.txt
tez do przywrocenia

2024-10-30 11:54 UTC, pdziekan commented on include/libcloudph++/blk_1m/formulae.hpp
Dodaj proszę odnosniki do papierow, z ktorych wziete sa te rownania (i nr rownan tam)

2024-10-30 11:54 UTC, pdziekan commented on include/libcloudph++/common/const_cp.hpp
> +      libcloudphxx_const(energy_over_mass, l_tri_evap, 2.5e6, si::joules / si::kilograms) // latent heat of evaporation
renaming l_tri to l_tri_evap can brake some codes that use libcloudphxx, let's see how tests go

2024-10-30 11:54 UTC, pdziekan commented on include/libcloudph++/blk_1m/formulae.hpp
> +        const quantity<si::temperature, real_t> T = th * std::pow((p/real_t(100000)/si::pascal), 0.286);
do liczenia T z theta bardziej elegancko bedzie uzyc funkcji exnera z include/common/theta_std (tak jak np. w adj_cellwise)

2024-10-30 11:54 UTC, pdziekan commented on include/libcloudph++/blk_1m/formulae.hpp
> +        real_t beta = (T/si::kelvins > real_t(213.16)*si::dimensionless()) ? real_t(0.1)+real_t(0.9)*(T-real_t(213.16)*si::kelvins)/(real_t(20)*si::kelvins) : real_t(0.1);
w porownaniu ladniej bedzie przemnozyc 213.16 przez kelviny, zamiast dzielic przez nie T

2024-10-30 11:54 UTC, pdziekan commented on include/libcloudph++/blk_1m/formulae.hpp
> +        quantity<divide_typeof_helper<si::dimensionless, si::time>::type, real_t> hom1 = (T/si::kelvins < real_t(233.16)*si::dimensionless()) ? (real_t(1)-std::exp(-dt/taunuc)) * std::max(real_t(0)*s
jak wyzej

2024-10-30 11:54 UTC, pdziekan commented on include/libcloudph++/blk_1m/formulae.hpp
> +        const quantity<si::temperature, real_t> T = th * std::pow((p/real_t(100000)/si::pascal), 0.286);
jak wyzej

2024-10-30 11:54 UTC, pdziekan commented on include/libcloudph++/blk_1m/rhs_cellwise.hpp
> +    void rhs_cellwise_nwtrph_ice(
duzo kodu powtorzonego z rhs_cellwise_nwtrph(), lepiej by bylo wywolac tutaj rhs_cellwise_nwtrph (albo jakas nowa funkcje zawierajaca wspolny kod) i dodac tylko kod dotyczacy lodu

2024-11-04 16:14 UTC, AgnieszkaMakulska commented on CMakeLists.txt
Wygląda na to, że testy przechodzą pomimo zmian w cmakelists

2024-11-04 16:25 UTC, AgnieszkaMakulska commented on bindings/python/blk_1m.hpp
Poprawiłam przy pomocy automatycznego formatowania w Clionie, ale nie wiem czy teraz jest tak jak powinno

2024-11-05 11:21 UTC, pdziekan commented on include/libcloudph++/blk_1m/rhs_cellwise.hpp
Myślę, że trzeba jeszcze dodać ograniczenia na maksymalne wartości zmian w czasie (rc_to_ria, rv_to_ria, itd.), żeby uniknąć ujemnych wartości rc, rv, itd. Coś takiego jest już zrobione na końcu funkcji rhs_cellwise_nwtrph. To prymitywny sposób, ale działa i nie sądze, żeby prowadził do znaczących błędów. W idealnym świecie takim ujemnym wartościom powinien pewnie zapobiegać bardziej zaawansowany algorytm całkowania numerycznego w czasie.

2024-11-06 12:13 UTC, AgnieszkaMakulska commented on include/libcloudph++/blk_1m/rhs_cellwise.hpp
Zastanawiam się, jak dobrze dodać ograniczenie na zmianę ria (ria zmniejsza się na skutek dwóch procesów, nukleacji lodu B (ria_to_rib) oraz topnienia (ria_to_rr). Dałam ograniczenie na każdy z tych procesów osobno, ale to nie gwarantuje że ich suma będzie odpowiednio mała

2024-11-12 15:02 UTC, AgnieszkaMakulska commented on include/libcloudph++/blk_1m/rhs_cellwise.hpp
> +        rr_to_rv = std::min(rr, rr_to_rv) / dt;
Chyba tutaj (i poniżej w rhs_cellwise_nwtrph_ice) powinno być
` rr_to_rv = std::min(rr/dt, rr_to_rv);`
zamiast
` rr_to_rv = std::min(rr, rr_to_rv) / dt;`?

W takiej wersji jak jest teraz, rr_to_rv (pochodna po czasie) jest chyba jeszcze dodatkowo dzielona przez dt

2024-12-02 14:02 UTC, merged